dist: xenial

os:
    - linux
    - osx 
#    - windows #No python support

env:
    global:
        - BLENDER_CACHE=$HOME/.cache/blender
    matrix:
#        - BLENDER_VERSION="2.78c"
        - BLENDER_VERSION="2.79b"
#        - BLENDER_VERSION="2.79-nightly"
#        - BLENDER_VERSION="2.80-nightly"
# 
# language: python
# python:
#     - 3.7

cache:
    apt: true
    directories:
        - $HOME/.cache/pip
        - ${BLENDER_CACHE}
addons:
    apt:
        packages:
            - blender
            - python

before_install:
    #- env
    - mkdir -p ${BLENDER_CACHE}
    - ls ${BLENDER_CACHE}
    - sudo pip install -r tests/requirements.txt --upgrade
    - yolk -l
    - cd $TRAVIS_BUILD_DIR

install:
    - python tests/get_blender.py ${BLENDER_VERSION}

script:
    - cd ${TRAVIS_BUILD_DIR}
    - python --version
    - ../blender-${BLENDER_VERSION}/blender --version
    - python tests/run_blender.py ${BLENDER_VERSION}

#after_success:
#    - codecov -f tests_output/coverage.xml

notifications:
    email:
        on_success: change
        on_failure: always
