dist: xenial

os:
    - linux
    - osx
#     - windows

env:
    global:
        - BLENDER_CACHE=$HOME/.cache/blender
    matrix:
#        - BLENDER_VERSION="2.78c"
        - BLENDER_VERSION="2.79b"
#        - BLENDER_VERSION="2.79-nightly"
#        - BLENDER_VERSION="2.80-nightly"

language: python
python:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 3.7 ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then 3.5 ; fi

cache:
    apt: true
    directories:
        - $HOME/.cache/pip
        - ${BLENDER_CACHE}
addons:
    apt:
        packages:
            - blender

before_install:
    #- env
    - mkdir -p ${BLENDER_CACHE}
    - ls ${BLENDER_CACHE}
    - pip install -r tests/requirements.txt --upgrade
    - yolk -l
    - cd $TRAVIS_BUILD_DIR

install:
    - python tests/get_blender.py ${BLENDER_VERSION}

script:
    - cd ${TRAVIS_BUILD_DIR}
    - ../blender-${BLENDER_VERSION}/blender --version
    - python tests/run_blender.py ${BLENDER_VERSION}

#after_success:
#    - codecov -f tests_output/coverage.xml

notifications:
    email:
        on_success: change
        on_failure: always
