name: test-fake-addon-example-from-local-wheel

on: 
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        blender-version: ["2.80"] #["2.78c", "2.79b", "2.80", "2.81a", "2.82", "2.83"]
        os: [ubuntu-latest] #[ubuntu-latest, windows-latest]
        #blender-version: ["2.80"]
        #os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Download and Test Blender ${{ matrix.blender-version }} x ${{ matrix.os}}
      run: |
        bash rebuild_pipreinstall_and_testexamples.sh
        cd examples/testing-fake-addon/
        python test_fake_addon_blender.py ${{ matrix.blender-version }} && python test_fake_addon_blender_advanced.py ${{ matrix.blender-version }} && python test_fake_addon_blender_prezipped_addon.py ${{ matrix.blender-version }}
